# Dependencies
excerpt_separator: <!--more-->

# Permalinks
permalink:         /:year/:month/:title

# Setup
title:             IDIUX
tagline:           Digital Product Design
url:               http://idiux.com
timezone:          Australia/Sydney
# plugins:           [jekyll-paginate]
# paginate:          1