# Dependencies
highlighter:       rouge
excerpt_separator: <!--more-->

# Permalinks
permalink:         /:categories/:year/:month/:title

# Setup
title:             IDIUX
tagline:           Digital Product Design
url:               http://idiux.com
# plugins:           [jekyll-paginate]
paginate:          1
baseurl:           
author:
  name:            Iain Dowling
  url:             https://twitter.com/idiux
#  email:          @gmail.com

# Custom vars
version:           1.0.0
github:
  repo:            https://idiux.github.io
